/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baocaoqlnv;

import MyEmployee.Model;
import MyEmployee.NhanVien;
import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class QLNV extends javax.swing.JFrame {
    DefaultTableModel model_tb;
    List<NhanVien> listNV;
    String filename=null;
    byte[] img_NV=null;
    public QLNV() {
        initComponents();
        set_table();
    }
    public void set_table(){
        String cl[] = {"Mã Số","Tên Nhân Viên","Giới Tính","Năm Sinh","SDT","Địa Chỉ","Email","Chức Vụ","Phòng Ban","Nhập Lương"};
        model_tb = new DefaultTableModel();
        model_tb.setColumnIdentifiers(cl);
        table.setModel(model_tb);
    }
    public void dataTable() throws Exception {
        Model nvm = new Model();
        listNV = nvm.load(); // Dùng để lấy dữ liệu từ CSDL để in lên bảng
        String gioitinh = null;
        while (model_tb.getRowCount() > 0) {
            model_tb.removeRow(0);
        }
        for (NhanVien nv : listNV) {
            if (nv.getGioitinh() == 1) {
                gioitinh = "Nam";
            } else {
                gioitinh = "Nữ";
            }
            model_tb.addRow(new String[]{nv.getMsnv(), nv.getHoten(), gioitinh, nv.getNgaysinh().toString(), nv.getSdt(), nv.getEmail(), nv.getDiachi(), nv.getPhongban(), nv.getChucvu(),nv.getLuong()});
                
        }
        model_tb.fireTableDataChanged();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtnmsnv = new javax.swing.JTextField();
        txtnhtnv = new javax.swing.JTextField();
        rdn = new javax.swing.JRadioButton();
        rdnu = new javax.swing.JRadioButton();
        txtns = new com.toedter.calendar.JDateChooser();
        txtsdt = new javax.swing.JTextField();
        txtdc = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        cbcv = new javax.swing.JComboBox<>();
        cbpb = new javax.swing.JComboBox<>();
        txtnl = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        btnnhapmoi = new javax.swing.JButton();
        btncapnhat = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        txtanh = new javax.swing.JLabel();
        btnChonAnh = new javax.swing.JButton();
        txtcanhbao = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 204, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");
        jLabel1.setMaximumSize(new java.awt.Dimension(300, 19));

        jLabel2.setText("Nhập mã số nhân viên");

        jLabel3.setText("Nhập họ tên nhân viên");

        jLabel4.setText("Nhập ngày tháng năm sinh");

        jLabel5.setText("Nhập email");

        jLabel6.setText("Nhập lương");

        jLabel7.setText("Giới tính");

        jLabel8.setText("Số điện thoại");

        jLabel9.setText("Địa chỉ");

        jLabel10.setText("Chức vụ");

        jLabel11.setText("Phòng ban");

        txtnhtnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnhtnvActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdn);
        rdn.setText("Nam");
        rdn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdnu);
        rdnu.setText("Nữ");

        txtdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdcActionPerformed(evt);
            }
        });

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        cbcv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trưởng Phòng", "Nhân Viên", " " }));

        cbpb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tài Chính", "Nhân Sự " }));

        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user-male-add-icon.png"))); // NOI18N
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnnhapmoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-contact-new-icon.png"))); // NOI18N
        btnnhapmoi.setText("Nhập mới");
        btnnhapmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhapmoiActionPerformed(evt);
            }
        });

        btncapnhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Text-Edit-icon.png"))); // NOI18N
        btncapnhat.setText("Cập nhật");
        btncapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatActionPerformed(evt);
            }
        });

        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Delete-icon.png"))); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/print-icon.png"))); // NOI18N
        btnin.setText("In");
        btnin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        btnChonAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/upload-icon.png"))); // NOI18N
        btnChonAnh.setText("Chọn Ảnh");
        btnChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhActionPerformed(evt);
            }
        });

        txtcanhbao.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        txtcanhbao.setForeground(new java.awt.Color(255, 0, 0));
        txtcanhbao.setText("Phải cập nhật ảnh");

        jLabel13.setText("Ảnh nhân viên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnthem)
                        .addGap(55, 55, 55)
                        .addComponent(btnnhapmoi)
                        .addGap(48, 48, 48)
                        .addComponent(btnxoa)
                        .addGap(68, 68, 68)
                        .addComponent(btncapnhat)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addComponent(btnChonAnh)
                                .addGap(115, 115, 115))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(btnin)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtnhtnv, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rdn)
                                        .addGap(42, 42, 42)
                                        .addComponent(rdnu))
                                    .addComponent(txtns, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                    .addComponent(txtsdt)
                                    .addComponent(txtdc)
                                    .addComponent(txtemail))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtnl, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbpb, javax.swing.GroupLayout.Alignment.LEADING, 0, 170, Short.MAX_VALUE)
                                    .addComponent(cbcv, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(txtnmsnv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtanh, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(txtcanhbao)))
                        .addGap(81, 81, 81))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(294, 294, 294))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtnmsnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtnhtnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rdn)
                                .addComponent(rdnu)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(cbcv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(cbpb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtcanhbao, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtanh, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChonAnh)
                        .addGap(21, 21, 21)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnnhapmoi)
                    .addComponent(btncapnhat)
                    .addComponent(btnxoa)
                    .addComponent(btnin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnhtnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnhtnvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnhtnvActionPerformed

    private void rdnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdnActionPerformed

    private void txtdcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdcActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
         try {
            NhanVien nv = new NhanVien();
            nv.setMsnv(txtnmsnv.getText());
            Model nvm = new Model();
            if (JOptionPane.showConfirmDialog(this, "Xác nhận xóa nhân viên " + txtnmsnv.getText(), "Xác nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                if (nvm.xoa(nv) == true) {
                    JOptionPane.showMessageDialog(this, "Đã xóa thành công !");
                } else {
                    JOptionPane.showMessageDialog(this, "Không thành công !");
                }
            }
            // load lại show data bên table
            dataTable();
        } catch (Exception e) {
        }      
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        if (txtnmsnv.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mã nhân viên không được rỗng !","Cảnh Báo", JOptionPane.WARNING_MESSAGE);
            txtnmsnv.setBackground(Color.yellow);
            txtnmsnv.requestFocus();
            return;
        } else {
            txtnmsnv.setBackground(Color.white);
        }
        if (txtsdt.getText().length() > 10) {
            JOptionPane.showMessageDialog(this, "SĐT không vượt 10 ký tự !","Cảnh Báo", JOptionPane.WARNING_MESSAGE);
            txtsdt.setBackground(Color.yellow);
            txtsdt.requestFocus();
            return;
        }
        try {
            int sdt = Integer.parseInt(txtsdt.getText());
            txtsdt.setBackground(Color.white);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "SĐT phải là số !","Cảnh Báo", JOptionPane.WARNING_MESSAGE);
            txtsdt.setBackground(Color.yellow);
            txtsdt.requestFocus();
            return;
        }

        try {
            NhanVien nv = new NhanVien();
            nv.setMsnv(txtnmsnv.getText());
            nv.setHoten(txtnhtnv.getText());
            nv.setChucvu(cbcv.getSelectedItem().toString());
            nv.setDiachi(txtdc.getText());
            nv.setEmail(txtemail.getText());
            nv.setLuong(txtnl.getText());
            nv.setGioitinh(rdn.isSelected() ? 1 : 0);
            nv.setPhongban(cbpb.getSelectedItem().toString());
            nv.setSdt(txtsdt.getText());
            java.util.Date chua = txtns.getDate();
            java.sql.Date sqlDate = new java.sql.Date(chua.getTime());
            nv.setNgaysinh(sqlDate);
            nv.setImg(img_NV);
            Model m = new Model();
            m.add(nv);
            JOptionPane.showMessageDialog(this, "Add seccesfull");
            dataTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Add fail" + e.getMessage());
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            dataTable();
             ImageIcon img_default = new ImageIcon("C:\\Users\\Acer\\Downloads\\anh\\hung.jpg");// ảnh mặc định
             txtanh.setIcon(img_default);
             txtcanhbao.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnnhapmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhapmoiActionPerformed
        txtnmsnv.setText("");
        txtemail.setText("");
        buttonGroup1.clearSelection();
        txtnhtnv.setText("");
        txtsdt.setText("");
        txtdc.setText("");
        txtns.setDate(new Date(0));
        cbpb.setSelectedIndex(0);
        cbcv.setSelectedIndex(0);
        txtnl.setText("");     
    }//GEN-LAST:event_btnnhapmoiActionPerformed

    private void btncapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatActionPerformed
        if (txtnmsnv.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Mã nhân viên không được rỗng !","Cảnh Báo", JOptionPane.WARNING_MESSAGE);
            txtnmsnv.setBackground(Color.yellow);
            txtnmsnv.requestFocus();
            return;
        } else {
            txtnmsnv.setBackground(Color.white);
        }
        try {
            NhanVien nv = new NhanVien();
            nv.setMsnv(txtnmsnv.getText());
            nv.setHoten(txtnhtnv.getText());
            nv.setDiachi(txtdc.getText());
            nv.setSdt(txtsdt.getText());
            nv.setEmail(txtemail.getText());
            nv.setPhongban(cbpb.getSelectedItem().toString());
            nv.setGioitinh(rdn.isSelected() ? 1 : 0);
            //Chuyển từ java.util.Date sang  java.sql.Date  => stackoverflow.com
            java.util.Date chuachuyen = txtns.getDate();
            java.sql.Date sqlDate;
            sqlDate = new java.sql.Date(chuachuyen.getTime());
            nv.setNgaysinh(sqlDate);

            nv.setChucvu(cbcv.getSelectedItem().toString());
            nv.setLuong(txtnl.getText());
           nv.setImg(img_NV);
            
            //nv.setImg(person_img);// person_img đang rỗng ảnh chưa được chọn nên chưa thể lấy ra

            Model nvm = new Model();
            nvm.capnhat(nv);
            JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thành công !");
            // load lại show data bên table
            dataTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không thành công !" + e.getMessage());
            System.out.println("" + e);
        }
    }//GEN-LAST:event_btncapnhatActionPerformed

    private void btnChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhActionPerformed
       JFileChooser chooser = new JFileChooser("Downloads"); // đường dẫn đến thư mục ảnh của nhân viên
        chooser.showOpenDialog(this);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageicon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(txtanh.getWidth(), txtanh.getHeight(), Image.SCALE_SMOOTH));
        txtanh.setIcon(imageicon);
        // Chuyển ảnh thành dữ liệu byte để lưu và sql
        try {
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for(int i; (i=fis.read(buf))!= -1;){
                bos.write(buf, 0, i);
            }
            img_NV = bos.toByteArray();
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnChonAnhActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int row = table.getSelectedRow();
        if (row >= 0) {
            String ma = (String) table.getValueAt(row, 0);
            for (NhanVien nv : listNV) {
                if (nv.getMsnv().equals(ma)) {
                    txtnmsnv.setText(nv.getMsnv());
                    txtdc.setText(nv.getDiachi());
                    txtnhtnv.setText(nv.getHoten());
                    txtemail.setText(nv.getEmail());
                    txtsdt.setText(nv.getSdt().trim());
                    if (nv.getGioitinh() == 1) {
                        rdn.setSelected(true);
                    } else {
                        rdnu.setSelected(true);
                    }
                    txtns.setDate(nv.getNgaysinh());
                    cbpb.setSelectedItem(nv.getPhongban());
                    cbcv.setSelectedItem(nv.getChucvu());
                    txtnl.setText(nv.getLuong().trim());
               
                    try {
                        byte[] img = nv.getImg();
                        ImageIcon imageicon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(txtanh.getWidth(), txtanh.getHeight(), Image.SCALE_SMOOTH));
                        txtanh.setIcon(imageicon);  
                        txtcanhbao.setVisible(false);
                    } catch (Exception e) {
                        
                       ImageIcon img_default = new ImageIcon("C:\\Users\\Acer\\Downloads\\anh\\hung.jpg");// ảnh mặc định
                       txtanh.setIcon(img_default);
                       txtcanhbao.setVisible(true);
                    }
                    
                    return;
                }
            }
        }
    }//GEN-LAST:event_tableMouseClicked

    private void btninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninActionPerformed
        try {
        String gioitinh = null;
        if(rdn.isSelected()) gioitinh="Nam";
        else gioitinh="Nữ";
        JOptionPane.showMessageDialog(this, "\nMã nhân viên: "+txtnmsnv.getText()+"\nHọ tên: "+txtnhtnv.getText()+"\nGiói tính: "+gioitinh+"\nNgày sinh: " +txtns.getDate().toString()
                                    +"\nSĐT: "+txtsdt.getText()+"\nEmail: "+txtemail.getText()+"\nĐịa chỉ: "+txtdc.getText()+"\nChức vụ: "+cbcv.getSelectedItem()
                                       +"\nLương cơ bản: "+txtnl.getText());
   
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu để In ","Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btninActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btncapnhat;
    private javax.swing.JButton btnin;
    private javax.swing.JButton btnnhapmoi;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbcv;
    private javax.swing.JComboBox<String> cbpb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdn;
    private javax.swing.JRadioButton rdnu;
    private javax.swing.JTable table;
    private javax.swing.JLabel txtanh;
    private javax.swing.JLabel txtcanhbao;
    private javax.swing.JTextField txtdc;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnhtnv;
    private javax.swing.JTextField txtnl;
    private javax.swing.JTextField txtnmsnv;
    private com.toedter.calendar.JDateChooser txtns;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables
}
